-- --------------------------------------------------------

--
-- Table structure for table `gobblegums`
--

CREATE TABLE `gobblegums` (
  `id` int NOT NULL,
  `name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `rarity` enum('Rare','Epic','Legendary','Ultra','Whimsical') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `color` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `essence_value` int NOT NULL,
  `pattern` enum('Instant','Timed','Conditional') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `activation_type` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `zombies_effect` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `doa4_effect` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `duration` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `short_description` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `gum_type` enum('New','Returning') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `icon_url` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `recyclable` tinyint(1) NOT NULL DEFAULT 1,
  `synergy` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tags` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sort_order` int NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `gobblegums`
--

-- Gobblegums INSERT statements
INSERT INTO `gobblegums` (`id`, `name`, `rarity`, `color`, `essence_value`, `pattern`, `activation_type`, `zombies_effect`, `doa4_effect`, `duration`, `short_description`, `gum_type`, `icon_url`, `recyclable`, `synergy`, `tags`, `sort_order`) VALUES
(1, 'Aftertaste', 'Rare', 'Blue', 500, 'Conditional', 'On Revive', 'Keep all your Perks after being revived.', 'On your next death, you retain your shields and chickens.', NULL, 'Retain all perks after revive.', 'New', '/assets/gobblegums/after_taste.webp', 1, 'Perkaholic', 'perk_protection,revive,survival,late_round,safety,objective_support', 1),
(2, 'Kill Joy', 'Rare', 'Blue', 500, 'Instant', 'On Use', 'Spawns an Insta-Kill Power-Up.', 'Activates Insta-Kill for 60 seconds. Bosses are unaffected.', NULL, 'Creates an Insta-Kill power-up instantly.', 'Returning', '/assets/gobblegums/kill_joy.webp', 1, 'Who''s Keeping Score?', 'insta_kill,powerup,offensive,revive_support,objective_push,essence_gain', 2),
(3, 'Cache Back', 'Rare', 'Blue', 500, 'Instant', 'On Use', 'Spawns a Max Ammo Power-Up.', 'Grants a max-level Ray Gun with unlimited ammo for 15 seconds.', NULL, 'Spawns a Max Ammo immediately.', 'Returning', '/assets/gobblegums/cache_back.webp', 1, NULL, 'max_ammo,powerup,ammo_sustain,team_support,resource_management', 3),
(4, 'Temporal Gift', 'Rare', 'Blue', 500, 'Conditional', 'On Next Time-Based Power-Up', 'The next time-based Power-Up you activate lasts longer.', 'The next Power-Up lasts twice as long and can stack with Fate of Fortune.', NULL, 'Extends the duration of your next timed Power-Up.', 'Returning', '/assets/gobblegums/temporal_gift.webp', 1, 'Fate of Fortune', 'powerup_extension,conditional,utility,solo_support,team_buff', 4),
(5, 'Stock Option', 'Rare', 'Blue', 500, 'Timed', 'On Use', 'For 60 seconds, ammo is taken directly from your stockpile instead of your weapon’s magazine.', 'Grants an Ammo pickup that increases your weapon level and prevents ammo drain for 15 seconds.', '60 seconds', 'Ammo pulls from reserve instead of the magazine.', 'Returning', '/assets/gobblegums/stock_option.webp', 1, 'Arsenal Accelerator, Insta-Kill', 'timed,ammo,fire_rate,aggressive_play,lmg_synergy,panic_button', 5),
(6, 'Anywhere But Here', 'Rare', 'Blue', 500, 'Instant', 'On Use', 'Instantly teleports you to a random location and releases a concussive blast that repels nearby zombies.', 'Grants a chicken companion for five minutes. Can be activated once every ten minutes.', NULL, 'Instantly teleport and blast away nearby zombies.', 'Returning', '/assets/gobblegums/anywhere_but_here.webp', 1, NULL, 'escape,panic_button,teleport,mobility,survival,regroup', 6),
(7, 'Power Keg', 'Rare', 'Blue', 500, 'Instant', 'On Use', 'Spawns a Full Power Power-Up, instantly restoring your Field Upgrade.', 'For 60 seconds, beneficial concussive waves periodically erupt at your location.', NULL, 'Spawns Full Power for instant Field Upgrade charge.', 'Returning', '/assets/gobblegums/power_keg.webp', 1, 'Arsenal Accelerator', 'field_upgrade,instant,powerup,team_support,revive_support,crowd_control,utility', 7),
(8, 'Tactical Diffusion', 'Rare', 'Blue', 500, 'Conditional', 'On Nuke Power-Up', 'The next Nuke Power-Up you activate does not explode and instead grants all players 2000 Essence.', 'For the next 90 seconds, each Nuke used (up to three) grants $2,000 for the Slayer Mart.', NULL, 'Disables the next Nuke and converts it into bonus Essence.', 'Returning', '/assets/gobblegums/tactical_diffusion.webp', 1, 'Double Points', 'essence_gain,conditional,nuke_conversion,economy,early_game_boost,team_support', 8),
(9, 'Arsenal Accelerator', 'Rare', 'Blue', 500, 'Timed', 'On Use', 'For 5 minutes, your Field Upgrade charges significantly faster.', 'Deploys three Energy Mines within 30 seconds.', '5 minutes', 'Speeds up Field Upgrade charge rate.', 'Returning', '/assets/gobblegums/arsenal_accelerator.webp', 1, 'Power Keg', 'field_upgrade,charge_rate,timed,team_support,solo_support,utility,objective_play', 9),
(10, 'Shields Up', 'Rare', 'Blue', 500, 'Timed', 'On Use', 'Refills your armor and doubles its strength for 3 minutes.', 'Grants a Barrel & Sawblade item lasting five minutes or until replaced or death.', '3 minutes', 'Refills armor and doubles its durability.', 'Returning', '/assets/gobblegums/shields_up.webp', 1, 'Nowhere But There!', 'armor,tank,timed,survivability,solo_support,revive_support,escape_tool', 10),
(11, 'Requipment', 'Epic', 'Purple', 1250, 'Timed', 'On Use', 'For 5 minutes, your Equipment slots automatically refill over time.', 'Grants a random combination of four Nukes and Boosts.', '5 minutes', 'Your equipment slowly refills over time.', 'New', '/assets/gobblegums/requipment.webp', 1, 'Vulture Aid', 'equipment_reload,utility,timed,resource_efficiency,solo_support,directed_mode_support', 11),
(12, 'Power Vacuum', 'Epic', 'Purple', 1250, 'Timed', 'On Use', 'For 5 minutes, kills have an increased chance to drop Power-Ups.', 'For 5 minutes, enemies have a small chance to drop useful items on death.', '5 minutes', 'Increases Power-Up drops from kills.', 'New', '/assets/gobblegums/power_vacuum.webp', 1, 'Power-Up based GobbleGums', 'powerup_farm,timed,resource_gain,team_support,round_management,loot_increase', 12),
(13, 'Respin Cycle', 'Epic', 'Purple', 1250, 'Instant', 'On Use', 'Re-spins the Mystery Box weapon to one of equal or higher rarity after it settles.', 'Awards either a helicopter or tank vehicle item.', NULL, 'Re-rolls settled Mystery Box weapon to same or higher rarity.', 'Returning', '/assets/gobblegums/respin_cycle.webp', 1, 'Crate Power, Wonderbar!', 'mystery_box,weapon_upgrade,instant,luck,early_game,essence_saving', 13),
(14, 'Dead Drop', 'Epic', 'Purple', 1250, 'Timed', 'On Use', 'For 5 minutes, Salvage and Equipment drop rates are greatly increased.', 'For 5 minutes, weapon drops occur roughly five times more often.', '5 minutes', 'Boosts Salvage, Equipment, and drop frequency.', 'Returning', '/assets/gobblegums/dead_drop.webp', 1, 'Vulture Aid (Picky Eater Augment)', 'salvage_farm,loot_increase,timed,resource_gain,equipment_spam,prep_tool', 14),
(15, 'Who''s Keeping Score?', 'Epic', 'Purple', 1250, 'Instant', 'On Use', 'Spawns a Double Points Power-Up.', 'For 5 minutes, treasure spawns at roughly five times the normal rate.', NULL, 'Instantly summons Double Points.', 'Returning', '/assets/gobblegums/whos_keeping_score.webp', 1, 'Kill Joy, Tactical Diffusion', 'double_points,essence_farm,powerup,early_game_boost,instant,resource_gain', 15),
(16, 'Free Fire', 'Epic', 'Purple', 1250, 'Timed', 'On Use', 'For 60 seconds, firing weapons consumes no ammo. Does not affect Wonder Weapons or Underbarrel Launchers.', 'For 60 seconds, firing weapons does not consume ammo.', '60 seconds', 'Shoot freely for 60 seconds with no ammo cost.', 'Returning', '/assets/gobblegums/free_fire.webp', 1, 'High-capacity weapons, Pack-a-Punch', 'ammo_free,damage_boost,timed,horde_clear,panic_button,survival', 16),
(17, 'Exit Strategy', 'Epic', 'Purple', 1250, 'Instant', 'On Use', 'Immediately triggers an Exfil vote and reduces zombie spawns during Exfil.', 'For 30 minutes, chicken eggs hatch extra coins.', NULL, 'Instantly start Exfil with reduced zombie spawns.', 'Returning', '/assets/gobblegums/exit_strategy.webp', 1, 'XP farming, Daily Challenges', 'exfil,objective_skip,instant,escape,round_management,xp_gain', 17),
(18, 'Profit Sharing', 'Epic', 'Purple', 1250, 'Timed', 'On Use', 'For 2 minutes, a portion of the Essence you earn is shared with nearby teammates and vice versa.', 'For 30 minutes, chicken eggs hatch additional cash shared evenly across all teammates.', '2 minutes', 'Share Essence gains with teammates nearby.', 'Returning', '/assets/gobblegums/profit_sharing.webp', 1, 'Double Points, Gift Card', 'team_support,essence_share,economy,timed,coop_boost,resource_gain', 18),
(19, 'Explosive Flourish', 'Epic', 'Purple', 1250, 'Timed', 'On Use', 'For 2 minutes, reloading triggers an explosion around you that damages nearby enemies.', 'Equips the player with a max-power RPG and grants unlimited ammo for 2 minutes.', '2 minutes', 'Reloads trigger damaging explosions around you.', 'Returning', '/assets/gobblegums/explosive_flourish.webp', 1, 'Speed Cola, Elemental Pop (Electric Cherry)', 'reload_damage,area_control,timed,panic_button,horde_control,close_range_combat', 19),
(20, 'Soda Fountain', 'Epic', 'Purple', 1250, 'Conditional', 'On Next Perk Purchase', 'The next Perk you buy grants an additional random Perk you don''t already own.', 'For up to 5 minutes, item spawns occur around four times more frequently.', NULL, 'Next perk purchase gives an extra random perk.', 'Returning', '/assets/gobblegums/soda_fountain.webp', 1, 'Perkaholic', 'perk_gain,power_spike,conditional,early_game,comeback_tool,essence_saving', 20),
(21, 'Nowhere But There', 'Epic', 'Purple', 1250, 'Instant', 'On Use', 'Instantly teleport to a random downed teammate and instantly revive all nearby players.', 'All players receive minimum respawn boosts and Nukes, downed players are revived, all Field Upgrades recharge, and Fate bonuses (Feet & Shield) are honored.', NULL, 'Teleport to a downed teammate and revive nearby allies.', 'Returning', '/assets/gobblegums/nowhere_but_there.webp', 1, 'Shields Up, Quick Revive', 'revive,team_support,instant,teleport,clutch_save,high_risk', 21),
(22, 'Round Off', 'Legendary', 'Orange', 3000, 'Conditional', 'On Round Transition', 'Prevents rounds from advancing for two rounds after the next round transition.', 'Ends the currently active round if under round 60. Has a 30-minute cooldown.', '2 rounds', 'Stops round progression for two rounds.', 'New', '/assets/gobblegums/round_off.webp', 1, 'Quest steps, Puzzle phases', 'round_control,conditional,breathing_room,solo_support,group_planning,objective_focus', 22),
(23, 'Armor Gettin’', 'Legendary', 'Orange', 3000, 'Instant', 'On Use', 'Instantly grants a three-plate Armor Vest and full plates.', 'Grants a one-plate Armor Vest with full plates, or if already equipped, awards a full refill of plates.', NULL, 'Instant full armor with a three-plate vest.', 'New', '/assets/gobblegums/armor_gettin.webp', 1, 'Shields Up, Jugger-Nog', 'armor,instant,tank,survival,starter_loadout,solo_friendly', 23),
(24, 'Idle Eyes', 'Legendary', 'Orange', 3000, 'Timed', 'On Use', 'For 30 seconds, all zombies ignore players and stand idle.', 'All zombies ignore players and stand idle for 30 seconds.', '30 seconds', 'Zombies ignore all players for 30 seconds.', 'Returning', '/assets/gobblegums/idle_eyes.webp', 1, 'Quick Revive, Round Off', 'crowd_control,timed,panic_button,revive_tool,objective_focus,solo_friendly', 24),
(25, 'Wall Power', 'Legendary', 'Orange', 3000, 'Conditional', 'On Next Wall Buy', 'The next weapon purchased from a wall is automatically Pack-A-Punched.', 'For one round, electric poles do not damage the player.', NULL, 'Next Wall Buy weapon comes Pack-A-Punched.', 'Returning', '/assets/gobblegums/wall_power.webp', 1, 'Cache Back', 'weapon_upgrade,conditional,early_power_spike,ammo_efficient,wallbuy_synergy,pp_support', 25),
(26, 'Flavor Hex', 'Legendary', 'Orange', 3000, 'Instant', 'On Use', 'Awards a random Ultra GobbleGum.', 'Awards a random Ultra GobbleGum.', NULL, 'Grants a random Ultra GobbleGum.', 'Returning', '/assets/gobblegums/flavor_hex.webp', 1, 'Ultra GobbleGums', 'random,instant,high_risk,high_reward,power_spike,luck_based', 26),
(27, 'Immolation Liquidation', 'Legendary', 'Orange', 3000, 'Instant', 'On Use', 'Spawns a Fire Sale Power-Up.', 'For 5 minutes, Holy Brimstone rains down onto enemies.', NULL, 'Summons a Fire Sale instantly.', 'Returning', '/assets/gobblegums/immolation_liquidation.webp', 1, 'Who''s Keeping Score?', 'fire_sale,instant,box_farming,weapon_hunting,team_coordination,early_game_power', 27),
(28, 'Support Group', 'Legendary', 'Orange', 3000, 'Instant', 'On Use', 'Grants ARC-XD, then Mangler Cannon, then Sentry Gun, then Disciple Injection in sequence.', 'For 5 minutes, only Cymbal Monkeys spawn as items during arena gameplay. Other item types are unaffected.', NULL, 'Grants a sequence of powerful Support items: ARC-XD → Mangler Cannon → Sentry Gun → Disciple Injection.', 'Returning', '/assets/gobblegums/support_group.webp', 1, 'Power Keg, Arsenal Accelerator', 'support_items,boss_damage,instant,power_spike,quest_tool,burst_dps', 28),
(29, 'Phoenix Up', 'Legendary', 'Orange', 3000, 'Instant', 'On Use', 'Instantly revives all teammates and allows them to keep all their Perks.', 'Grants yourself and all teammates one extra life.', NULL, 'Revives all teammates instantly, preserving their Perks.', 'Returning', '/assets/gobblegums/phoenix_up.webp', 1, 'Quick Revive, Nowhere But There', 'revive,team_support,instant,perk_protection,clutch_save,full_team_recovery', 29),
(30, 'Modified Chaos', 'Legendary', 'Orange', 3000, 'Timed', 'On Use', 'Greatly reduces all Ammo Mod cooldowns for 1 minute.', 'Greatly reduces all Ammo Mod cooldowns for 1 minute.', '1 minute', 'Greatly reduces all Ammo Mod cooldowns for 1 minute.', 'Returning', '/assets/gobblegums/modified_chaos.webp', 1, 'Elemental Pop (Chill Berry Augment), Ammo Mods', 'ammo_mods,damage_boost,timed,elemental_synergy,boss_fights,horde_control', 30),
(31, 'On the House', 'Legendary', 'Orange', 3000, 'Instant', 'On Use', 'Spawns a random Perk Power-Up that grants a free Perk to all players.', 'Purchasing from the Slayer Mart grants one extra random item of any value.', NULL, 'Spawns a free random Perk for the whole team.', 'Returning', '/assets/gobblegums/on_the_house.webp', 1, 'Soda Fountain, Perkaholic', 'perk_gain,team_buff,instant,free_perk,essence_saving,mid_game_power', 31),
(32, 'Wall to Wall Clearance', 'Legendary', 'Orange', 3000, 'Timed', 'On Use', 'For 30 seconds, all Wall Buy weapons cost only 10 Essence.', 'For 2 minutes, a free Nuke deploys on your position every 10 seconds.', '30 seconds', 'Wall Buys cost only 10 Essence for 30 seconds.', 'Returning', '/assets/gobblegums/wall_to_wall_clearance.webp', 1, 'Wall Power, Who’s Keeping Score?', 'economy,wallbuy_discount,team_saving,timed,early_game_power,resource_efficiency', 32),
(33, 'Crate Power', 'Legendary', 'Orange', 3000, 'Conditional', 'On Next Mystery Box Spin', 'The next weapon taken from the Mystery Box is automatically Pack-A-Punched.', 'On your next death, you do not lose your gems.', NULL, 'Next Mystery Box pull becomes Pack-A-Punched.', 'Returning', '/assets/gobblegums/crate_power.webp', 1, 'Immolation Liquidation, Time Out', 'mystery_box,weapon_upgrade,conditional,early_game_power,fire_sale_synergy,pap_boost', 33),
(34, 'Gift Card', 'Ultra', 'Red', 5000, 'Instant', 'On Use', 'Instantly grants 30,000 Essence. Cannot be combined with other bonuses.', 'Grants $30,000 to spend in the Slayer Mart.', NULL, 'Instantly gain 30,000 Essence.', 'New', '/assets/gobblegums/gift_card.webp', 1, 'Hidden Power', 'economy,instant,ultra,essence_boost,comeback,high_value', 34),
(35, 'Perkaholic', 'Ultra', 'Red', 5000, 'Instant', 'On Use', 'Grants the player every available Perk instantly.', 'Awards a random Field Upgrade, a random Ammo Mod, a Level 1 Armor Vest, and a 30-minute Chicken.', NULL, 'Instantly receive all available Perks.', 'Returning', '/assets/gobblegums/perkaholic.webp', 1, 'Hidden Power, Shields Up', 'perk_full_loadout,instant,ultra,comeback,early_power,synergy_boost', 35),
(36, 'Wonderbar!', 'Ultra', 'Red', 5000, 'Conditional', 'On Next Mystery Box Spin', 'The next weapon taken from the Mystery Box is guaranteed to be a Wonder Weapon.', 'For 30 minutes, at the start of each round, flip a coin to either become a Mutant or receive a Chicken.', NULL, 'Next Mystery Box pull becomes a Wonder Weapon.', 'Returning', '/assets/gobblegums/wonderbar.webp', 1, 'Crate Power, Respin Cycle, Immolation Liquidation', 'wonder_weapon,conditional,ultra,mystery_box,boss_fight_ready,quest_synergy,fire_sale_combo', 36),
(37, 'Time Out', 'Ultra', 'Red', 5000, 'Timed', 'On Activation', 'For 3 minutes, all Normal and Special enemies are cleared, the round ends, and no new enemies spawn during the duration.', 'For 30 minutes, within 30 seconds of each new Arena round, a free Nuke Bomb drops at your position.', '3 Minutes', 'Clears enemies and stops spawning for 3 minutes.', 'Returning', '/assets/gobblegums/time_out.webp', 1, 'Crate Power, Hidden Power, Perk purchases, Der Wunderfizz routing', 'ultra,timed,round_control,safe_window,revives,shopping_phase,der_wunderfizz', 37),
(38, 'Near Death Experience', 'Ultra', 'Red', 5000, 'Timed', 'On Activation', 'For 3 minutes or up to 5 revives, players can revive or be revived instantly by standing near each other. Revived players retain all their Perks.', 'For each Nuke dropped in the next 10 seconds, gain an extra life.', '3 Minutes (or 5 Revives)', 'Instant proximity revives that preserve all Perks.', 'Returning', '/assets/gobblegums/near_death_experience.webp', 1, 'Phoenix Up, Shields Up, Revive-focused builds, High round boss fights', 'ultra,timed,revives,perk_protection,team_support,high_round,boss_fight', 38),
(39, 'Reign Drops', 'Ultra', 'Red', 5000, 'Instant', 'On Activation', 'Spawns all core Power-Ups at once, including Insta-Kill, Max Ammo, Double Points, Full Armor, Random Perk, Fire Sale, Full Power, Bonus Points, and Nuke.', 'At the next Slayer Mart store, all items have a random discount between 20% and 50%.', NULL, 'Instantly spawns every major Power-Up at once.', 'Returning', '/assets/gobblegums/reign_drops.webp', 1, 'Main Quest steps, early-game setup, Fire Sale chains, survival emergencies', 'ultra,instant,powerups,team_support,setup,main_quest,panic_button', 39),
(40, 'Hidden Power', 'Ultra', 'Red', 5000, 'Instant', 'On Activation', 'Instantly upgrades your currently held weapon to Legendary rarity.', 'For 10 minutes, every weapon picked up has maximum power.', NULL, 'Instantly upgrades your current weapon to Legendary quality.', 'Returning', '/assets/gobblegums/hidden_power.webp', 1, 'Wall Power, Perkaholic, early-game snowball, main quest prep', 'ultra,instant,weapon_upgrade,legendary,early_power_spike,loadout_synergy', 40),
(41, 'Newtonian Negation', 'Whimsical', 'Rainbow', 100, 'Timed', 'On Activation', 'Zombies killed will float upward instead of falling normally.', 'Same humorous effect applies.', NULL, 'Zombies float upward when killed.', 'Returning', '/assets/gobblegums/newtonian_negation.webp', 1, NULL, 'whimsical,fun,cosmetic,timed,visual_effect', 41),
(42, 'Indiegestion', 'Whimsical', 'Rainbow', 100, 'Timed', 'On Activation', 'Zombies release exaggerated flatulence effects when killed.', 'Same humorous visual gag effect applies.', NULL, 'Zombies emit goofy flatulence effects when killed.', 'Returning', '/assets/gobblegums/indiegestion.webp', 1, NULL, 'whimsical,fun,cosmetic,humor,timed', 42),
(43, 'Rainburps', 'Whimsical', 'Rainbow', 100, 'Timed', 'On Activation', 'Zombies belch sparkly rainbow bubbles upon death.', 'Same humorous rainbow bubble effect applies.', NULL, 'Zombies release rainbow bubble bursts when killed.', 'Returning', '/assets/gobblegums/rainburps.webp', 1, NULL, 'whimsical,cosmetic,fun,visual_effect,timed', 43),
(44, 'Quacknarok', 'Whimsical', 'Rainbow', 100, 'Timed', 'On Activation', 'Zombies wear rubber ducky inner tubes, adding a humorous visual twist.', 'Same comedic appearance effect applies.', NULL, 'Zombies appear wearing rubber ducky float tubes.', 'Returning', '/assets/gobblegums/quacknarok.webp', 1, NULL, 'whimsical,fun,visual_effect,cosmetic,timed,duck_theme', 44),
(45, 'Die Pitched', 'Whimsical', 'Rainbow', 100, 'Timed', 'On Activation', 'Zombies emit high-pitched comedic voices as they approach and attack.', 'Same humorous high-pitch voice effect applies.', NULL, 'Zombies speak and scream in high-pitched voices.', 'Returning', '/assets/gobblegums/die_pitched.webp', 1, NULL, 'whimsical,fun,audio_effect,cosmetic,timed,high_pitch', 45),
(46, 'Holiday Cheer', 'Whimsical', 'Rainbow', 100, 'Timed', 'On Activation', 'Zombies appear with festive decorations, adding a fun holiday-themed visual flair.', 'Same festive cosmetic effect applies.', NULL, 'Gives zombies goofy holiday-themed decorations.', 'Returning', '/assets/gobblegums/holiday_cheer.webp', 1, NULL, 'whimsical,holiday,cosmetic,fun,visual_effect,timed', 46);

-- --------------------------------------------------------

--
-- Table structure for table `gobblegum_tips`
--

CREATE TABLE `gobblegum_tips` (
  `id` int NOT NULL,
  `gobblegum_id` int NOT NULL,
  `tip` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `sort_order` int NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `gobblegum_tips`
--

-- Gobblegum Tips INSERT statements
INSERT INTO `gobblegum_tips` (`id`, `gobblegum_id`, `tip`, `sort_order`) VALUES
(1, 1, 'Provides perk insurance when combined with Perkaholic.', 1),
(2, 1, 'Great safety net for high rounds when one down can ruin the run.', 2),
(3, 1, 'Useful during puzzles or Easter Egg steps where a down can cost progress.', 3),
(4, 2, 'Combo with Double Points or Who''s Keeping Score? to generate large Essence bursts.', 1),
(5, 2, 'Perfect emergency tool to secure revives when your team is overwhelmed.', 2),
(6, 2, 'Use before difficult objectives to gain a temporary offensive advantage.', 3),
(7, 3, 'Coordinate with your team to avoid wasting a Max Ammo when one may already be active.', 1),
(8, 3, 'Use strategically instead of spending Essence at Ammo Caches, especially on expensive Pack-a-Punch weapons.', 2),
(9, 3, 'Ideal for camo grinding or challenges on weapons with small ammo reserves.', 3),
(10, 4, 'Use just before picking up a strong timed Power-Up like Insta-Kill for maximum benefit.', 1),
(11, 4, 'Extend Fire Sale duration to give your team more time to roll the Mystery Box.', 2),
(12, 4, 'A great solo boost since extended Power-Ups greatly improve survival windows.', 3),
(13, 5, 'Great with LMGs or ARs with large reserve ammo for nonstop firing.', 1),
(14, 5, 'Use when trapped in tight spaces to shoot continuously without reloading.', 2),
(15, 5, 'Prevent reload downtime during powerful buffs like Arsenal Accelerator or Insta-Kill.', 3),
(16, 6, 'Use when you''re isolated from your squad to quickly reposition and rejoin the team.', 1),
(17, 6, 'Escape overwhelming hordes and secure breathing room thanks to the concussive blast on arrival.', 2),
(18, 6, 'A free mobility tool when you''re far from fast travel or don’t want to spend Essence.', 3),
(19, 7, 'Combine with Arsenal Accelerator to rapidly chain multiple Field Upgrades.', 1),
(20, 7, 'Use during tense moments to quickly access supportive Field Upgrades for revives.', 2),
(21, 7, 'Grants near-instant access to tools like Frost Blast or Energy Mine for strong area control.', 3),
(22, 8, 'Use before picking up a Nuke to avoid losing potential Essence and gain guaranteed income instead.', 1),
(23, 8, 'Combine with Double Points to maximize the bonus Essence payout.', 2),
(24, 8, 'Great to use early in a match to accelerate your weapon and perk upgrades.', 3),
(25, 9, 'Use immediately after deploying a Field Upgrade to start recharging it faster.', 1),
(26, 9, 'Excellent for solo runs where your Field Upgrade acts as your lifeline.', 2),
(27, 9, 'During Directed mode or Easter Egg steps, keep your Field Upgrade charged for quick problem solving.', 3),
(28, 10, 'Use during desperate retreats to survive heavy damage while escaping large hordes.', 1),
(29, 10, 'Pair with Nowhere But There! to safely survive the chaos when teleporting into a downed teammate''s location.', 2),
(30, 10, 'Excellent for solo players who rely on strong armor to avoid consuming Self-Revives.', 3),
(31, 11, 'Lets you stay stocked on equipment without taking chip damage from looting.', 1),
(32, 11, 'Save Salvage by letting Requipment refill basic items automatically.', 2),
(33, 11, 'Great for Decoy-heavy strategies in Directed mode or story-focused objectives.', 3),
(34, 12, 'Use when low on Power-Up focused GobbleGums like Kill Joy or Cache Back to restock naturally.', 1),
(35, 12, 'Great for helping teammates survive since anyone can pick up the extra Power-Ups you spawn.', 2),
(36, 12, 'Activate shortly after a round begins to maximize the five-minute window.', 3),
(37, 13, 'Combine with Crate Power and Wonderbar! to secure higher-tier or Wonder Weapons reliably.', 1),
(38, 13, 'The Mystery Box re-closes and re-spins before settling, so be patient.', 2),
(39, 13, 'Use in early rounds or when low on Essence to avoid wasting points on bad box rolls.', 3),
(40, 14, 'Activate a round before difficult objectives to farm Salvage for Ammo Mods and Support items.', 1),
(41, 14, 'With increased Equipment drops, use grenades and tacticals freely without worrying about running out.', 2),
(42, 14, 'Pairs well with the Picky Eater Vulture Aid augment for even more Equipment drops.', 3),
(43, 15, 'Activate when a large horde is present to maximize Double Points value.', 1),
(44, 15, 'Use early in the match to quickly open doors, buy perks, and upgrade weapons.', 2),
(45, 15, 'Pop before Pack-a-Punching if you''re short on Essence to secure the upgrade sooner.', 3),
(46, 16, 'Use when swarmed to mow down large groups and regain control.', 1),
(47, 16, 'Pairs extremely well with Pack-a-Punched high fire rate weapons for huge damage output.', 2),
(48, 16, 'Activate when you''re low on ammo to fight your way toward an Ammo Cache safely.', 3),
(49, 17, 'Use when rounds get too chaotic and you want a safe Exfil for bonus XP.', 1),
(50, 17, 'Great fallback when you reach the Exfil area but miss the prompt due to a round transition.', 2),
(51, 17, 'Trigger Exfil to complete Daily Challenges without advancing the Main Quest path.', 3),
(52, 18, 'Activate while grouped tightly with your full squad to maximize shared Essence gains.', 1),
(53, 18, 'Great for helping the entire team reach Pack-A-Punch or expensive wall weapon unlocks.', 2),
(54, 18, 'Stay with the group until the effect ends—splitting early wastes potential shared income.', 3),
(55, 19, 'Use when being closed in by a horde—each reload creates a shockwave that clears space.', 1),
(56, 19, 'Pairs extremely well with Speed Cola to trigger more explosive reloads in shorter intervals.', 2),
(57, 19, 'Stack with Elemental Pop’s Electric Cherry augment to deal both explosive and electric damage on reload.', 3),
(58, 20, 'Buy easily accessible Perks first so the bonus Perk is guaranteed to be something rare or harder to obtain.', 1),
(59, 20, 'A great recovery tool after losing all Perks—helps rebuild your loadout quickly.', 2),
(60, 20, 'Use when you''re slightly underpowered to get an unexpected power boost from a bonus Perk.', 3),
(61, 21, 'Best used when multiple teammates are down together—teleport in and revive them instantly.', 1),
(62, 21, 'Reload before activating since you will teleport straight into danger.', 2),
(63, 21, 'Avoid teleporting to lone downed players far from the team—it can split the group and make the situation worse.', 3),
(64, 22, 'Use when you need uninterrupted breathing room to reset, heal, or re-equip—especially in solo runs.', 1),
(65, 22, 'Activate to give your whole squad time to regroup, plan, and prepare for upcoming objectives.', 2),
(66, 22, 'Ideal for long Easter Egg attempts when you need quiet time to solve steps or organize items.', 3),
(67, 23, 'Use at the start of a match to get a three-plate vest immediately and save Essence on early armor purchases.', 1),
(68, 23, 'Great for solo runs—jump straight into tank mode without needing upgrades or crafting.', 2),
(69, 23, 'Provides a major survivability spike in DOA4 where armor plates massively improve durability.', 3),
(70, 24, 'Use during Main Quest steps that require uninterrupted interaction, especially in solo runs.', 1),
(71, 24, 'Great for emergency revives—zombies freeze long enough to bring the whole squad back safely.', 2),
(72, 24, 'Communicate before activating in squads so everyone can maximize the 30-second window.', 3),
(73, 25, 'Activate just before buying the specific Wall Buy weapon you intend to use long-term.', 1),
(74, 25, 'Choose Wall Buys positioned in high-traffic or choke-point areas to benefit from constant nearby ammo.', 2),
(75, 25, 'Pair with Cache Back for a guaranteed Max Ammo to support your powered-up Wall Buy.', 3),
(76, 26, 'Use when you need a burst of power—any Ultra GobbleGum can swing a tough situation in your favor.', 1),
(77, 26, 'Remember that you must pop the awarded Ultra GobbleGum after using Flavor Hex to activate its effect.', 2),
(78, 26, 'Activate during a calm moment to plan the best use of the Ultra GobbleGum you receive.', 3),
(79, 27, 'Activate and rush the nearest Mystery Box—Fire Sale time is short, so maximize every second.', 1),
(80, 27, 'Have teammates spread across different Mystery Boxes to avoid waiting and increase total spins.', 2),
(81, 27, 'Plan ahead by positioning your team at multiple boxes before using the GobbleGum.', 3),
(82, 28, 'Use the ARC-XD first to unlock the Mangler Cannon, then the Sentry Gun, and finally the Disciple Injection—plan the order for maximum impact.', 1),
(83, 28, 'Save Support Group for boss encounters or Main Quest steps where its sequence of Support items can deal huge burst damage.', 2),
(84, 28, 'Create space before activating—each Support item takes a few seconds to prep, and popping it while surrounded is risky.', 3),
(85, 29, 'Use when multiple teammates are down—Phoenix Up revives everyone instantly and preserves their full Perk setup.', 1),
(86, 29, 'Communicate before activating so teammates don''t waste other revives or GobbleGums unnecessarily.', 2),
(87, 29, 'No range limit—teammates are revived no matter where they are on the map, perfect for chaotic split-up moments.', 3),
(88, 30, 'Equip Ammo Mods before using Modified Chaos—its cooldown reduction only matters when an Ammo Mod is active.', 1),
(89, 30, 'Combine with Elemental Pop and its Chill Berry Minor Augment for even faster Ammo Mod procs.', 2),
(90, 30, 'Use during intense fights or boss encounters when frequent elemental procs can swing the battle.', 3),
(91, 31, 'Grab your essential Perks first so the bonus Perk has a higher chance of being a rare one.', 1),
(92, 31, 'Whoever picks up the spawned Perk Power-Up, the entire squad gets the Perk—use it to rally team strength.', 2),
(93, 31, 'Activate between rounds to avoid losing the free Perk by getting downed immediately after.', 3),
(94, 32, 'Use early in a match to save massive amounts of Essence on Wall Buy weapons for the entire squad.', 1),
(95, 32, 'Give teammates a heads-up before activating so everyone can reach their preferred Wall Buy in time.', 2),
(96, 32, 'Stack with Wall Power for an extremely cheap Pack-A-Punched Wall Buy immediately.', 3),
(97, 33, 'Use during a Fire Sale to maximize your odds of getting the perfect weapon before it becomes Pack-A-Punched.', 1),
(98, 33, 'Combine with Time Out to safely browse Mystery Box rolls without zombies interrupting you.', 2),
(99, 33, 'Best used early game before Pack-A-Punch becomes accessible, saving Essence for other upgrades.', 3),
(100, 34, 'Use early with Hidden Power to reach a Legendary Pack-A-Punch setup far sooner than normal.', 1),
(101, 34, 'Perfect comeback tool after being revived with no resources—instantly rebuild your entire loadout.', 2),
(102, 34, 'Use to recover from expensive purchases or misallocations and quickly stabilize your economy.', 3),
(103, 35, 'Use early to save massive amounts of Essence and unlock your full perk setup immediately.', 1),
(104, 35, 'Combine with Hidden Power for a guaranteed Legendary weapon after fully perk-stacking your Operator.', 2),
(105, 35, 'A perfect recovery tool—pop it after a late-game down to instantly regain your entire perk loadout.', 3),
(106, 36, 'Use before Main Quest steps that require specific Wonder Weapons so you’re guaranteed to get one from the box.', 1),
(107, 36, 'Grab the Wonder Weapon and drop it for a teammate if they''re struggling—strong squad > strong solo.', 2),
(108, 36, 'Combine with Crate Power for a guaranteed Pack-A-Punched Wonder Weapon; activate during a Fire Sale for maximum value.', 3),
(109, 37, 'Activate when things get chaotic to reset the area, revive teammates, and reorganize the squad safely.', 1),
(110, 37, 'Use at the end of a round to guarantee three minutes without enemy spawns or mid-round threats.', 2),
(111, 37, 'Use the downtime to hit Der Wunderfizz, purchase Perks, or combo with Hidden Power + Crate Power for fast setup.', 3),
(112, 38, 'Use during chaotic moments like horde rushes or boss fights to revive multiple teammates instantly without losing control.', 1),
(113, 38, 'If you go down, teammates can instantly revive you while preserving all your Perks—great for endgame survival.', 2),
(114, 38, 'Activate before entering a dangerous fight; popping it too late risks losing the ability before it helps.', 3),
(115, 39, 'Use during overwhelming situations to instantly get every core Power-Up and stabilize the fight.', 1),
(116, 39, 'Using it early in a run creates a massive advantage with Fire Sale, Bonus Points, and a Perk Power-Up all at once.', 2),
(117, 39, 'Pop it during Main Quest steps where teammates are occupied with objectives to compensate for the reduced firepower.', 3),
(118, 40, 'Equip the weapon you want upgraded in your loadout so you can transform it into a Legendary gun immediately.', 1),
(119, 40, 'Use early in the match to breeze through low rounds while saving Salvage for Ammo Mods and Crafting Table upgrades.', 2),
(120, 40, 'Combine with Wall Power for an instant Pack-A-Punched Legendary weapon, and add Perkaholic for a huge early-game power spike.', 3),
(121, 41, 'Use when you want a silly, lighthearted match—this Gum alters visuals but not gameplay.', 1),
(122, 41, 'Great for casual maps or chill sessions where you want some comic relief.', 2),
(123, 42, 'Use for a humorous match—adds silly sound and visual effects without changing gameplay.', 1),
(124, 42, 'Great for casual runs or when you want to lighten the mood with some goofy zombie deaths.', 2),
(125, 43, 'Use when you want a colorful and silly visual effect while slaying zombies.', 1),
(126, 43, 'Perfect for casual or relaxed matches where you just want fun visual flair.', 2),
(127, 44, 'Use when you want comedic relief—the zombies look ridiculous with floaty duck tubes.', 1),
(128, 44, 'Perfect for fun runs or when streaming for entertainment value.', 2),
(129, 45, 'Adds lighthearted comedy by giving zombies squeaky, high-pitched voices.', 1),
(130, 45, 'Great for relaxed sessions or streams where you want funny audio moments.', 2),
(131, 46, 'Use during casual matches to bring goofy festive decorations to the zombie horde.', 1),
(132, 46, 'Great for holiday-themed sessions or anytime you want cheerful visual fun.', 2);
